# Generated by Django 4.2.4 on 2024-01-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='date',
        ),
    ]
