# Generated by Django 4.2.4 on 2024-01-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_created_at_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='unit_price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
