# Generated by Django 4.2.4 on 2024-01-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_invoice_invoicef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='invoice',
            new_name='forkey',
        ),
    ]
